method: 'grid'

metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model: 
      value: 'autoencoder'
    task:
      value: 'gaze'
    segment:
      value: 12
    hidden_sizes: 
      #value: [512]
      value: [128]
    alpha:
      value: 0
    lr: 
      values: [1e-3, 3e-4, 1e-4, 3e-5, 3e-3]
    weight_decay: 
      values: [1e-4, 1e-5, 1e-6]
  
    batch_size:
      value: 16
    
    epoch:
      value: 30

    ckpt:
      value: 'checkpoints/autoencoder5'
    result_root_dir:
      value: 'results/autoencoder5'
    pretrained_dir:
      value: 'pretrained5'