method: 'grid'

metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model: 
      value: 'autoencoder'
    task:
      value: 'gaze'
    segment:
      value: 12
    segment_length:
      value: 90
    hidden_sizes: 
      #value: [512]
      value: [128]
    
    alpha:
      value: 0
    lr: 
      value: 1e-3
    weight_decay: 
      value: 1e-5
    batch_size:
      value: 16
    strategy:
      value: 'ddp'
    
    epoch:
      value: 1

    ckpt:
      value: 'checkpoints/test'