method: 'grid'
name: 'multi'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model:
      value: 'masktransformer'

    hidden_size: 
      value: 1024
    segment:
      value: 2  # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 90
    frozen:
      value: True
    
    pretrained:
      value: 'pretrained'
    feature_filling:
      value: 'repeat'

    lr: 
      values: [3e-5, 5e-6, 3e-6]
    weight_decay: 
      value: 1e-5
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'

    test_idx:
      value: 30

    
    n_layer:
      value: 12
    n_head:
      value: 16
    activation_function: 
      value: 'gelu'
    n_ctx:
      value: 216
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 150

    ckpt:
      value: 'checkpoints/v21/' 

    