method: 'grid'
name: 'multi'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model:
      value: 'masktransformer'

    hidden_size: 
      value: 1024
    segment:
      value: 12
    frozen:
      value: True
    
    pretrained:
      value: True
    feature_filling:
      value: 'repeat'
    feature_mask:
      value: 'multi'

    lr: 
      value: 3e-4
    weight_decay: 
      value: 1e-6
    alpha:
      value: 0.25
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'

    
    n_layer:
      value: 48
    n_head:
      value: 16
    activation_function: 
      value: 'relu'
    n_ctx:
      value: 216
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 1

    ckpt:
      value: 'checkpoints/test'

    