method: 'grid'
name: 'multi'
metric: 
    name: 'val_f1'
    goal: 'maximize'   

parameters: 
    seed:
      value: 42

    model:
      value: 'masktransformer'

    hidden_size: 
      value: 1024
    segment:
      value: 12  # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 90
    frozen:
      value: True
    
    pretrained:
      value: 'pretrained'
    feature_filling:
      value: 'repeat'

    lr: 
      value: 3e-5
    weight_decay: 
      value: 1e-6
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'

    test_idx:
      values: [30]

    
    n_layer:
      value: 12 # 12
    n_head:
      value: 16 # 16
    activation_function: 
      value: 'gelu'
    n_ctx:
      value: 216
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 50

    ckpt:
      value: 'checkpoints/ablation/continuous'

    comment:
      value: 'multi with continuous featurization'

    