method: 'grid'
name: 'multi'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model:
      value: 'masktransformer'

    hidden_size: 
      value: 1024
    segment:
      value: 12
    frozen:
      value: True
    
    pretrained:
      value: True
    feature_filling:
      value: 'repeat'

    lr: 
      value: 5e-4
    weight_decay: 
      value: 1e-5
    alpha:
      value: 0
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'

    test_idx:
      values: [26, 27, 28, 29]

    
    n_layer:
      value: 12
    n_head:
      value: 16
    activation_function: 
      value: 'relu'
    n_ctx:
      value: 216
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 150

    ckpt:
      value: 'checkpoints/transformer_vq/kfold'

    