method: 'grid'
name: 'multi'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    hidden_size: 
      value: 512
    segment:
      value: 12
    frozen:
      values: [False, True]
    
    pretrained:
      value: True
    feature_filling:
      value: 'repeat'

    lr: 
      values: [3e-4, 5e-4]
    weight_decay: 
      value: 1e-6
    alpha:
      values: [0, 0.25, 0.5, 0.75, 1]
    batch_size:
      value: 32

    
    n_layer:
      value: 48
    n_head:
      value: 16
    activation_function: 
      value: 'relu'
    n_ctx:
      value: 216
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 18

    epoch:
      value: 100

    result_root_dir:
      value: 'results/transformer9'
    ckpt:
      value: 'checkpoints/transformer9'

    