method: 'grid'

metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42

    model: 
      value: 'transformer'
    hidden_size: 
      value: 512
    segment:
      value: 12
    task:
      value: None
    frozen:
      values: [False, True]
    multi_task:
      value: True
    mask_ratio:
      value: 0.3333333
    eval_type:
      value: 2
    pretrained:
      value: True
    feature_filling:
      value: 'repeat'

    lr: 
      values: [0.005, 0.003]
    weight_decay: 
      value: 1e-5
    warmup_ratio:
      values: [0.1, 0.2]
    batch_size:
      value: 4
    alpha:
      value: 1

    n_layer:
      value: 24
    n_head:
      value: 16
    activation_function: 
      value: 'relu'
    n_ctx:
      value: 144
    resid_pdrop:
      value: 0.1
    attn_pdrop:
      value: 0.1
    n_bundle:
      value: 12

    epoch:
      value: 20