method: 'grid'
name: 'vqvae'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42
    model:
      value: 'vqvae'

    task:
      values: ['pose']
    segment:
      value: 30 # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 36

    test_idx:
      value: 30

    hidden_sizes: 
      value: [1024]
    h_dim:
      value: 128
    kernel:
      value: 3
    stride:
      value: 1
    res_h_dim:
      value: 32
    n_res_layers:
      value: 2
    n_embeddings:
      values: [512, 1024, 256]
    embedding_dim:
      value: 32 # (18, 32)

    temperature:
      values: [1, 0.5]
    beta:
      value: 0.25
    lamb:
      values: [0, 0.25]
    vq_weight:
      value: 1

    lr: 
      values: [5e-4, 3e-4]
    weight_decay: 
      value: 1e-6
    batch_size:
      value: 32
    strategy:
      value: 'ddp'
    

    epoch:
      value: 150

    ckpt:
      value: 'checkpoints/vqvae_v19'

    comment:
      value: '30 segments with 32 embeding dim and sampling on segment and grid search on lamb' 

    