method: 'grid'
name: 'vqvae'
metric: 
    name: 'val_loss'
    goal: 'minimize'   

parameters: 
    seed:
      value: 42
    model:
      value: 'vqvae'

    task:
      values: ['gaze', 'headpose', 'pose']
    segment:
      value: 12 # 6 * 180 / 4 * 270 / 2 * 540
    segment_length:
      value: 90

    test_idx:
      values: [30]

    hidden_sizes: 
      value: [1024]
    h_dim:
      value: 128
    kernel:
      value: 3
    stride:
      value: 1
    res_h_dim:
      value: 32
    n_res_layers:
      value: 2
    n_embeddings:
      value: 512
    embedding_dim:
      value: 32
    beta:
      value: 0.25

    lr: 
      value: 5e-4
    weight_decay: 
      value: 1e-6
    batch_size:
      value: 32
    strategy:
      value: 'ddp_find_unused_parameters_true'
    

    epoch:
      value: 1

    ckpt:
      value: 'checkpoints/vqvae/test'

    